application:
  configuration:
    rabbit:
      queueName: "PaymentsQueue"
  payments:
    eventStoreBaseDir: "${java.io.tmpdir}/example-axon/payments"

server:
  port: 38080

spring:
  jmx:
    enabled: false
