application:
  configuration:
    axon:
      eventStore:
        baseDir: "${java.io.tmpdir}/example-axon/payments"
  payments:
    key: "value"

server:
  port: 38080

spring:
  jmx:
    enabled: false
