application:
  configuration:
    axon:
      eventStore:
        baseDir: "${java.io.tmpdir}/example-axon/payments"
    rabbitmq:
      exchange:
        name: "Axon.EventBus"
      queue:
        name: "PaymentsQueue"
  payments:
    key: "value"

server:
  port: 38080

spring:
  jmx:
    enabled: false
