application:
  configuration:
    axon:
      eventStoreBaseDir: "${java.io.tmpdir}/example-axon/payments"
    rabbit:
      queueName: "PaymentsQueue"
  payments:
    key: "value"

server:
  port: 38080

spring:
  jmx:
    enabled: false
