application:
  configuration:
    axon:
      eventStore:
        baseDir: "${java.io.tmpdir}/example-axon/management"
    rabbitmq:
      exchange:
        name: "Axon.EventBus"
      queue:
        name: "ManagementQueue"
  management:
    key: "value"

server:
  port: 18080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  jmx:
    enabled: false
