application:
  configuration:
    axon:
      eventStoreBaseDir: "${java.io.tmpdir}/example-axon/management"
    rabbit:
      queueName: "ManagementQueue"
  management:
    key: "value"

server:
  port: 18080

spring:
  datasource:
    driverClassName: "org.h2.Driver"
    url: "jdbc:h2:mem:management;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: "sa"
    password: ""
  jpa:
    show-sql: false
    ddl-auto: create
    hibernate:
      naming-strategy: "org.hibernate.cfg.ImprovedNamingStrategy"
  jmx:
    enabled: false
