application:
  configuration:
    rabbit:
      queueName: "RegistrationsQueue"
  registrations:
    eventStoreBaseDir: "${java.io.tmpdir}/example-axon/registrations"

server:
  port: 28080

spring:
  jmx:
    enabled: false
