application:
  configuration:
    axon:
      eventStore:
        baseDir: "${java.io.tmpdir}/example-axon/registrations"
    rabbitmq:
      exchange:
        name: "Axon.EventBus"
      queue:
        name: "RegistrationsQueue"
  registrations:
    key: "value"


server:
  port: 28080

spring:
  jmx:
    enabled: false
