application:
  configuration:
    axon:
      eventStoreBaseDir: "${java.io.tmpdir}/example-axon/registrations"
    rabbit:
      queueName: "RegistrationsQueue"
  registrations:
    key: "value"


server:
  port: 28080

spring:
  jmx:
    enabled: false
