application:
  configuration:
    axon:
      eventStoreBaseDir: "${java.io.tmpdir}/example-axon/registrations"
    rabbit:
      host: "localhost"
      port: 5672
      username: guest
      password: guest
      exchangeName: "Axon.EventBus"
      queueName: "RegistrationsQueue"
  registrations:
    key: "value"


server:
  port: 28080

spring:
  jmx:
    enabled: false
